version: '3.4'

services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: ./webapi/Dockerfile
    networks:
      - defaultnetwork
    ports:
      - 5000:80


  webapi-with-prometheus:
    container_name: webapi-with-prometheus
    build:
      context: .
      dockerfile: ./webapi-with-prometheus/Dockerfile
    networks:
      - defaultnetwork
    ports:
      - 5002:80

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.38.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - defaultnetwork 
    restart: always



volumes:
  prometheus_volume:

networks:
  defaultnetwork:
    name: BackendNetwork